random.permutation # 将给定序列乱序  
random.permutation[a:b] # 先将给定序列乱序，再从中截取a:b的序列（a和b为截取索引）

In [13]:
import numpy.random as random
random.seed(7)
rand_a = random.permutation([0,1,2,3,4,5,6,7,8,9])
rand_aa = rand_a[0:3]

print(rand_a)
print(rand_aa)

[8 5 0 2 1 9 7 3 6 4]
[8 5 0]


In [11]:
import torch
import numpy as np
cmc = torch.IntTensor(10).zero_()
print(cmc)
rows_good = np.array([8,5,7,3,2,4,1])
print(rows_good)
t1 = rows_good[0]
print(t1)
t2 = cmc[rows_good[0]:]
print(t2)
cmc[rows_good[0]:] = 1
print(cmc)
cmc2 = torch.IntTensor(10).zero_()
cmc2[rows_good[0:]] = 1
print(cmc2)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
[8 5 7 3 2 4 1]
8
tensor([0, 0], dtype=torch.int32)
tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 1], dtype=torch.int32)
tensor([0, 1, 1, 1, 1, 1, 0, 1, 1, 0], dtype=torch.int32)
